[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
auditingx = "9KoFUYa8gA9FxE5X1JfTcmjyCjvSzkjiW41BymM7mUZK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000 
validator_file = "test-ledger/validator.yml"

[test.validator]
compute_unit_limit = 1000000